---
name: "💥 Vulnerability"
description: Create a new ticket for a vulnerability in the repo.
title: "💥 - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: vulnerability-description
    attributes:
      label: "What is the vulnerability?"
      description: Short and explicit description of the vulnerability and its impact.
      placeholder: The repo contains the vulnerability xxx... And it is important to fix it as... and the related CVE is...
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: "Any solutions in mind?"
      description: Optionally, share with us a solution that you think would solve the vulnerability.
      placeholder: Changing X to Y would fix this vulnerability issue...
    validations:
      required: false

